#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(50, "priority scheduler")
def test_sched_stats_and_pass():
    r.run_qemu(shell_script([
        'scheduletest 12 8 4 3000 300000 1'  # 示例参数
    ]), timeout=300)
    r.match(r'(?m)^C+B+A+$')
    r.match(r'(?m)^verify\(eps=\d+\):\s*PASS$')


@test(50, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests'
    ]), timeout=500)
    r.match('^ALL TESTS PASSED$')

run_tests()